### ISSUE TITLE
PersistentVolume support

### ISSUE THREAD

**Issue by mtyurt** [docker/compose-on-kubernetes#10]
Is there any plan to add PersistentVolume support as in 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/ ?

**Comment by simonferquel** [comment]
Actually we already translates data volume mounts as persistent volume claims. We don't expose all the pvc options though and that would be a most welcome addition.

**Comment by simonferquel** [comment]
An extract from internal docs (that will come to the repo in a following PR) about volumes:
#### Volumes

There are several different types of volumes that are handled by Compose for
Kubernetes.

The following Compose snippet declares a service that uses a persistent volume:

```yaml
version: "3.6"

services:
  mysql:
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
```

A
[_PersistentVolumeClaim_](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
with an empty provider is created when one specifies a persistent volume for a
service. This requires that Kubernetes has a default storage provider
configured.

The following Compose snippet declares a service with a host bind mount:

```yaml
version: "3.6"

services:
  web:
    image: nginx:alpine
    volumes:
      - type: bind
        source: /srv/data/static
        target: /opt/app/static
```

Host bind mounts are supported but note that an absolute source path is
required.

The following Compose snippet declares a service with a tmpfs mount:

```yaml
version: "3.6"

services:
  web:
    image: nginx:alpine
    tmpfs:
      - /tmpfs
```

Mounts of type tmpfs create an empty directory which is stored in memory for the
life of the pod.
