### ISSUE TITLE
Support for secrets

### ISSUE THREAD

**Issue by alvarocantador** [docker/compose-on-kubernetes#12]
Is there support for [secrets](https://kubernetes.io/docs/concepts/configuration/secret/) in place?

**Comment by simonferquel** [comment]
We have support in place for that yes (alongside with configmaps). We still have to curate some aspects of the internal compose on kubernetes documentation (we'll do that in a PR soon), but here is the secrets and configmaps related section:

#### Secrets

Secrets in Swarm are a simple key-value pair. In Kubernetes, a secret has a name
and then a map of keys to values. This means that the mapping is non-trivial.
The following Compose snippet shows a service with two secrets:

```yaml
version: "3.6"

services:
  web:
    image: nginx:alpine
    secrets:
      - mysecret
      - myexternalsecret

secrets:
  mysecret:
    file: ./my_secret.txt
  myexternalsecret:
    external: true
```

When deployed using the Docker CLI, a Kubernetes secret will be created from the
client-local file `./my_secret.txt`. The secret's name will be `my_secret`, it
will have a single key `my_secret.txt` whose value will be the contents of the
file. As expected, this secret will then be mounted to `/run/secrets/my_secret`
in the pod.

External secrets need to be created manually by the user using `kubectl` or the
relevant Kubernetes APIs. The secret name must match the Swarm secret name, its
key must be `file` and the associated value the secret value:

```bash
$ echo -n 'external secret' > ./file
$ kubectl create secret generic myexternalsecret --from-file=./file
secret "myexternalsecret" created
```

#### Configs

Configs work the same as [secrets](#secrets).
