### ISSUE TITLE
Deploying with GPU

### ISSUE THREAD

**Issue by tkg61** [docker/compose-on-kubernetes#161]
Is there any way to specify whether or not a container should give given access to an Nvidia GPU inside the k8s cluster? I know compose 3 doesn't work with GPUs yet but wasn't sure if it could be added into a compose that is then deployed on k8s

I tried adding: 
```
    deploy:
      resources:
        limits:
          nvidia.com/gpu: 1
```

but the nvidia.com/gpu:1 key was not found
