### ISSUE TITLE
Invalid Gopkg.toml file

### ISSUE THREAD

**Issue by carolynvs** [docker/compose-on-kubernetes#92]
I wanted to give you a heads up that your Gopkg.toml file is invalid and causes problems for people trying to depend on your library.

Entries like this

https://github.com/docker/compose-on-kubernetes/blob/3fcc42fdbcf6e37cc1da2363369846a74a7ef0dd/Gopkg.toml#L25-L27

should be 

```toml
[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.5"
```

`revision` in the Gopkg.toml means a specific git commit hash. `version` indicates a tag.

Otherwise consumers of your library run into this error when running `dep ensure` when another package requires one of these projects and uses `version` correctly

```
Solving failure: Could not introduce github.com/docker/compose-on-kubernetes@v0.4.18, as it has a dependency on k8s.io/apimachinery with constraint kubernetes-1.11.5, which has no overlap with existing constraint kubernetes-1.11.5 from (root)
```
